version: '3.7'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - INSTANCE_NAME=lyra-searxng
      - BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET=lyra_secret_key
      - SEARXNG_ENABLE_METRICS=false
      - SEARXNG_ENABLE_API=true
      - SEARXNG_BYPASS_API_KEY=lyra_test_api_key
    restart: unless-stopped